version: "3"
services:
  registry:
    image: apache/nifi-registry:latest
    ports:
      - 18080:18080 
    environment:
      - NIFI_REGISTRY_WEB_HTTP_HOST=0.0.0.0
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=1g
    volumes:
      - ./git_versioned_flow:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./providers.xml:/opt/nifi-registry/nifi-registry-current/conf/providers.xml
      - ./database:/opt/nifi-registry/nifi-registry-current/database
